In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
df = pd.read_csv('/Users/aaliyahgritly/Desktop/Bebo Stuff/Projects/Telco IBM Churn Project/Telco Churn Data (ML).csv')

In [3]:
df.head()

,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,churn_flag,tenure_groups,high_value_customer,number_of_services,contract_risk,contract_risk_score,senior_alone_flag,vulnerability_score,monthly_charge_groups,monthly_charge_score
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,1,0-12 Months,0,3,High Risk,2,0,2,Medium,1
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,1,0-12 Months,1,1,High Risk,2,0,1,High,2
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,1,0-12 Months,1,5,High Risk,2,0,1,High,3
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,1,25-48 Months,1,6,High Risk,2,0,0,High,3
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,1,49+ Months,1,6,High Risk,2,0,1,High,3


# MACHINE LEARNING
* Turn the dataset into something a machine learning model can learn from to try to predict whether a customer will churn
* ML models only understand numerical data ex vulnerability_score not categorical data ex contract_risk

1) Define target and features (ML models learn by first taking input (X), then learn relationship, then predict outcome (Y), which is why we seperate target and features or x and y)

In [7]:
target = 'churn_flag' # Define the target variable for modeling (churn)

# y is the target variable (churn), while x contains all the features (charges, services, etc) except the target variable, which will be used for modeling.
X = df.drop(columns = [target])
y = df[target]

2) Encoding (convert categories into numbers), because ML models can only read numbers

In [9]:
# Convert categorical variables into dummy/indicator variables for modeling
X_encoded = pd.get_dummies(x, drop_first = True)

X_encoded.head()

NameError: name 'x' is not defined

3) Train/Test Split splits data into a training set (model learns form it) and a test set which we evaluate the model on.

In [13]:
from sklearn.model_selection import train_test_split # Import the train_test_split function from scikit-learn

# Split the data into training and testing sets (test_size = 0.2 means 20% for testing, 80% for training)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size = 0.2, random_state = 42)

4) Scaling to normalize numbers because different scales can confuse models, and to avoid data leakage

In [18]:
from sklearn.preprocessing import StandardScaler # Import the StandardScaler for feature scaling

scaler = StandardScaler() # Create an instance of the StandardScaler

X_train_scaled = scaler.fit_transform(X_train) # Learn the scaling parameters from the training data and apply the transformation to the training data
X_test_scaled = scaler.transform(X_test) # Apply the same scaling transformation to the test data (using the parameters learned from the training data)

5) Build first model

In [19]:
from sklearn.linear_model import LogisticRegression 
# LogisticRegression is a commonly used algorithm for binary classification problems, which is suitable for predicting churn (yes/no).

model = LogisticRegression(max_iter = 1000) # Create an instance of the Logistic Regression model with a maximum of 1000 iterations
model.fit(X_train_scaled, y_train) # Fit the model to the training data
# .fit basically means "train the model on the training data" - it learns the relationships between the features and the target variable (churn) based on the training data.

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

6) Make predictions

In [20]:
y_pred = model.predict(X_test_scaled) # Use the trained model to make predictions on the new test data

7) Evaluate Model (very important)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
# The classification_report function provides a detailed report of the precision, recall, f1-score, and support for each class (churn vs no churn) to evaluate the model's performance.
# precision: Of all the customers predicted to churn, how many actually churned? (True Positives / (True Positives + False Positives))
# recall: Of all the customers who actually churned, how many were correctly predicted to churn? (True Positives / (True Positives + False Negatives))
# f1-score: The harmonic mean of precision and recall, providing a single metric that balances both 

# recall matters most, because missing a churn customer (false negative) is more costly than incorrectly predicting a non-churn customer as a churn customer (false positive).

print(classification_report(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1009
           1       0.99      0.98      0.98       400

    accuracy                           0.99      1409
   macro avg       0.99      0.99      0.99      1409
weighted avg       0.99      0.99      0.99      1409



Precision: 0.99 means when the model predicts a customer to churn, they are correct 99% of the time  
Recal: 0.98 mean out of all actuall churners, the model catches 98% of them 

In [ ]:
print(confusion_matrix(y_test, y_pred)) # Print the confusion matrix to see the counts of true positives, true negatives, false positives, and false negatives

[[1004    5]
 [   8  392]]


- 1004: Predicted No Churn (0), Actual No Churn (0) (True Negatives) - Correctly predicted 1004 customers as not churning ✅
- 8: Predicted No Churn (0), Actual Churn (1) (False Negatives) - 8 customers churned but model missed them
- 5: Predicted Churn (1), Actual No Churn (0) (False Positives) - Predicted 5 customers as churning when they actually did not churn so false alarm
- 392: Predicted Churn (1), Actual Churn (1) (True Positives) - Correctly predicted 392 customers as churning ✅

# Evalute model and move to next step
* The model was cheating as it had access to columns like churn_flag and churn_score, basically giving it the correct answers
* Now we remove the columns and try again

In [4]:
df = pd.read_csv('/Users/aaliyahgritly/Desktop/Bebo Stuff/Projects/Telco IBM Churn Project/Telco Churn Data (ML).csv')

In [5]:
y = df['churn_flag']

In [6]:
features = [
    'gender', 'senior_citizen', 'partner', 'dependents',
    'tenure_months', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup',
    'device_protection', 'tech_support', 'streaming_tv',
    'streaming_movies', 'contract', 'paperless_billing',
    'payment_method', 'monthly_charges',
    'tenure_groups', 'number_of_services',
    'contract_risk', 'senior_alone_flag',
    'vulnerability_score'
]

X = df[features]

In [7]:
print(X.columns)

Index(['gender', 'senior_citizen', 'partner', 'dependents', 'tenure_months',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'tenure_groups',
       'number_of_services', 'contract_risk', 'senior_alone_flag',
       'vulnerability_score'],
      dtype='object')


In [8]:
print('churn_flag' in X.columns)

False


In [9]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [13]:
y_pred = model.predict(X_test_scaled)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1009
           1       0.70      0.57      0.63       400

    accuracy                           0.81      1409
   macro avg       0.77      0.74      0.75      1409
weighted avg       0.80      0.81      0.80      1409



* Recall 0.57: The model only catches 57% of churners, or misses 43% of customers who will churn.
* Accuracy 0.81: 81% accuracy looks good, but thats only because most customers stay.

* Recall vs Precision: Higher precision usually means fewer false alarms, but misses more churners, while higher recall catches more churners, but more false alarms
* The model is good at identifying non-churners, but struggling to catch churners.

In [15]:
confusion_matrix(y_test, y_pred)

array([[914,  95],
       [173, 227]])

* 914 predicted to not churn, and actually didnt churn ✅
* 173 predicted to not churn, but actually churned
* 95 predicted to churn, but did not churn
* 227 predicted to churn, and actually churned ✅

* The model misses churners because churn behaviour is complicated, not every customer churns for the same reason. Some churn because of pricing, others because of customer service, and others because competitors offered better deals. Also, some churn signals like gender, city, partner, etc maybe weak indicators of churn, so the model gets more noisy information.
* Businesses prefer a higher recall becuase missing churners means losing revenue. So, even if precision is 50%, but recall is 90%+, this accurately predicts churners but many false alarms, which isnt that bad.

## Improving the model
* There is a class imbalance in the data. The model is biased to non-churners, as the dataset has much more non-churners than churners.
* We have to make the model pay extra attention to churn customers as they are fewer.

In [ ]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression(max_iter = 1000, class_weight = 'balanced') 
# class_weight = 'balanced' tells the model to automatically adjust the weights of the classes (churn vs no churn) to handle any imbalance in the target variable, which can help improve performance when one class is much more frequent than the other.

model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :ter

In [17]:
y_pred = model.predict(X_test_scaled)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.74      0.81      1009
           1       0.55      0.81      0.66       400

    accuracy                           0.76      1409
   macro avg       0.73      0.77      0.74      1409
weighted avg       0.81      0.76      0.77      1409



In [19]:
confusion_matrix(y_test, y_pred)

array([[746, 263],
       [ 76, 324]])

* Recall: Previous model was 57%, now its 81%, so that is very good, but the cost is that precision decreased so there many more fals positives (more loyal customers are incorrectly flagged as churn risks)

# Why is the model predicitng churn?

In [ ]:
coefficients = pd.DataFrame({
    'Feature': X_encoded.columns,
    'Coefficient': model.coef_[0]
})
# this creates a df called coefficients with two columns: 'Feature' and 'Coefficient'
# model.coef_ is an array of shape (1, n_features) containing the coefficients for each feature in the logistic regression model. We take the first row (model.coef_[0]) to get the coefficients for our features and create a DataFrame to easily analyze and sort them.
# A positive coefficient means churn likelihood increases as the feature value increases, while a negative coefficient means churn likelihood decreases as the feature value increases.
coefficients = coefficients.sort_values(
    by='Coefficient',
    ascending=False
)
# this sorts the coefficients DataFrame in descending order based on the 'Coefficient' column, so that the features with the highest positive impact on churn are at the top and those with the most negative impact are at the bottom.
coefficients.head(15)

,Feature,Coefficient
12,internet_service_Fiber optic,0.310799
7,partner_Yes,0.215707
28,paperless_billing_Yes,0.177396
1,monthly_charges,0.161725
11,multiple_lines_Yes,0.149116
30,payment_method_Electronic check,0.141390
4,vulnerability_score,0.131109
34,tenure_groups_49+ Months,0.125850
23,streaming_tv_Yes,0.102024
25,streaming_movies_Yes,0.095733


* Some of these make sense like fiber optic customers (pay more, expect more), paperless billing (more digitally engaged, easier to switch providers), electronic check (manually make electronic payments instead of automated billing), and monthly charges (higher monthly charge = higher churn possibility).
* Some dont make sense, like having a partner. The model isnt saying having a partner causes churn, but that in THIS dataset, partnered customers correlate slightly with churn. Also, parterned customers maybe using fiber internet more, have higher monthly charges, etc.

In [21]:
coefficients.tail(15)

,Feature,Coefficient
16,online_backup_No internet service,-0.041566
13,internet_service_No,-0.041566
14,online_security_No internet service,-0.041566
29,payment_method_Credit card (automatic),-0.046872
9,phone_service_Yes,-0.065131
33,tenure_groups_25-48 Months,-0.110993
21,tech_support_Yes,-0.116926
36,contract_risk_Medium Risk,-0.138796
26,contract_One year,-0.138796
15,online_security_Yes,-0.156051


# These tell us that there are redundant features that are confusing the model like having both tenure groups and tenure months, so we remove them and try again.

In [4]:
features = [
    'gender', 'senior_citizen', 'partner', 'dependents',
    'tenure_months', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup',
    'device_protection', 'tech_support', 'streaming_tv',
    'streaming_movies', 'contract', 'paperless_billing',
    'payment_method', 'monthly_charges',
    'number_of_services', 'senior_alone_flag',
    'vulnerability_score'
]

X = df[features]

In [5]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :ter

In [13]:
y_pred = model.predict(X_test_scaled)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.73      0.81      1009
           1       0.54      0.80      0.65       400

    accuracy                           0.75      1409
   macro avg       0.72      0.77      0.73      1409
weighted avg       0.80      0.75      0.76      1409



In [15]:
confusion_matrix(y_test, y_pred)

array([[741, 268],
       [ 81, 319]])

In [16]:
coefficients = pd.DataFrame({
    'Feature': X_encoded.columns,
    'Coefficient': model.coef_[0]
})

coefficients = coefficients.sort_values(
    by='Coefficient',
    ascending=False
)
coefficients.head(15)

,Feature,Coefficient
12,internet_service_Fiber optic,0.312413
7,partner_Yes,0.207717
28,paperless_billing_Yes,0.173056
1,monthly_charges,0.152126
30,payment_method_Electronic check,0.150976
11,multiple_lines_Yes,0.141346
4,vulnerability_score,0.131522
23,streaming_tv_Yes,0.102167
25,streaming_movies_Yes,0.098906
10,multiple_lines_No phone service,0.062127


# Test Tree-Bases models like Random Forest for comparison
* Random forest is less sensitive to scaling and often performs better than LogisticRegression

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf_model = RandomForestClassifier(n_estimators = 100, random_state = 42, class_weight = 'balanced')

rf_model.fit(X_train, y_train) # Use X_train NOT X_train_scaled because Random Forests do not require feature scaling.

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [19]:
rf_pred = rf_model.predict(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1009
           1       0.66      0.51      0.57       400

    accuracy                           0.79      1409
   macro avg       0.74      0.70      0.72      1409
weighted avg       0.78      0.79      0.78      1409

[[906 103]
 [198 202]]


# Model Tuning 
* Using probabilities instead of predictions (you will get probability of churn ex 0.82 instead of yes/no)

In [ ]:
# model.predict_proba(X_test_scaled) predicts how likely a customer is to churn
# [:, 1] returns only the probabilities of churn (the second column of the output, where the first column would be the probability of not churning)
# All results are stored in the variable y_probs
y_probs = model.predict_proba(X_test_scaled)[:, 1]

In [ ]:
import numpy as np

# Logistic Regression uses 0.5 as default threshold (> 0.5 churn, <= 0.5 no churn) so we changed the threshold to 0.35 to see if it improves recall (catching more churn customers)
# np.where is similar to an if-statement: if p > 0.35, then predict 1 (churn), else predict 0 (no churn)
y_pred_new = np.where(y_probs > 0.35, 1, 0)

In [23]:
print(classification_report(y_test, y_pred_new))
print(confusion_matrix(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.95      0.62      0.75      1009
           1       0.49      0.91      0.64       400

    accuracy                           0.71      1409
   macro avg       0.72      0.77      0.69      1409
weighted avg       0.82      0.71      0.72      1409

[[629 380]
 [ 35 365]]


* Recall decreased but precision increased. 
* This results in catching almost every churn customer, but the trade-off is now there are many false alarms